BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE resultados CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE resultados (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id NUMBER(19) NOT NULL,
    paciente_nombre VARCHAR2(200) NOT NULL,
    medico_id NUMBER(19) NOT NULL,
    medico_nombre VARCHAR2(200) NOT NULL,
    laboratorio VARCHAR2(150) NOT NULL,
    tipo_analisis VARCHAR2(150) NOT NULL,
    descripcion CLOB NOT NULL,
    resultado_detalle CLOB NOT NULL,
    estado VARCHAR2(20) NOT NULL CHECK (estado IN ('PENDIENTE', 'EN_PROCESO', 'COMPLETADO', 'ENTREGADO')),
    fecha_analisis DATE NOT NULL,
    fecha_entrega DATE,
    observaciones CLOB,
    valores_referencia CLOB,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_resultados_paciente ON resultados(paciente_id);
CREATE INDEX idx_resultados_medico ON resultados(medico_id);
CREATE INDEX idx_resultados_laboratorio ON resultados(laboratorio);
CREATE INDEX idx_resultados_estado ON resultados(estado);
CREATE INDEX idx_resultados_fecha ON resultados(fecha_analisis);

INSERT INTO resultados (
    paciente_id, paciente_nombre, medico_id, medico_nombre, laboratorio, 
    tipo_analisis, descripcion, resultado_detalle, estado, 
    fecha_analisis, fecha_entrega, observaciones, valores_referencia,
    fecha_registro, fecha_actualizacion
) VALUES (
    3, 
    'Carlos Rodríguez Silva', 
    2, 
    'Dra. María González López', 
    'Laboratorio Clínico San José', 
    'Hemograma Completo', 
    'Análisis de sangre completo para evaluar glóbulos rojos, blancos y plaquetas',
    'Hemoglobina: 14.5 g/dL, Leucocitos: 7500/μL, Plaquetas: 250000/μL',
    'COMPLETADO',
    TO_DATE('2024-10-25', 'YYYY-MM-DD'),
    TO_DATE('2024-10-27', 'YYYY-MM-DD'),
    'Valores dentro de parámetros normales',
    'Hemoglobina: 12-16 g/dL, Leucocitos: 4000-11000/μL, Plaquetas: 150000-400000/μL',
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP
);

INSERT INTO resultados (
    paciente_id, paciente_nombre, medico_id, medico_nombre, laboratorio, 
    tipo_analisis, descripcion, resultado_detalle, estado, 
    fecha_analisis, fecha_entrega, observaciones, valores_referencia,
    fecha_registro, fecha_actualizacion
) VALUES (
    3, 
    'Carlos Rodríguez Silva', 
    2, 
    'Dra. María González López', 
    'Laboratorio Médico Central', 
    'Perfil Bioquímico', 
    'Análisis de glucosa, colesterol, triglicéridos y función hepática',
    'Glucosa: 95 mg/dL, Colesterol Total: 185 mg/dL, Triglicéridos: 140 mg/dL, TGO: 28 U/L, TGP: 32 U/L',
    'ENTREGADO',
    TO_DATE('2024-10-28', 'YYYY-MM-DD'),
    TO_DATE('2024-10-30', 'YYYY-MM-DD'),
    'Valores normales. Se recomienda mantener dieta balanceada',
    'Glucosa: 70-100 mg/dL, Colesterol: <200 mg/dL, Triglicéridos: <150 mg/dL',
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP
);

INSERT INTO resultados (
    paciente_id, paciente_nombre, medico_id, medico_nombre, laboratorio, 
    tipo_analisis, descripcion, resultado_detalle, estado, 
    fecha_analisis, fecha_entrega, observaciones, valores_referencia,
    fecha_registro, fecha_actualizacion
) VALUES (
    3, 
    'Carlos Rodríguez Silva', 
    2, 
    'Dra. María González López', 
    'Laboratorio de Análisis Avanzados', 
    'Perfil Tiroideo', 
    'Evaluación de función tiroidea mediante TSH, T3 y T4',
    'TSH: 2.5 mUI/L, T4 Libre: 1.2 ng/dL, T3 Total: 110 ng/dL',
    'EN_PROCESO',
    TO_DATE('2024-11-01', 'YYYY-MM-DD'),
    NULL,
    'Análisis en proceso. Resultados disponibles en 48 horas',
    'TSH: 0.4-4.0 mUI/L, T4 Libre: 0.8-1.8 ng/dL, T3 Total: 80-180 ng/dL',
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP
);

INSERT INTO resultados (
    paciente_id, paciente_nombre, medico_id, medico_nombre, laboratorio, 
    tipo_analisis, descripcion, resultado_detalle, estado, 
    fecha_analisis, observaciones, valores_referencia,
    fecha_registro, fecha_actualizacion
) VALUES (
    4, 
    'Ana Martínez Pérez', 
    2, 
    'Dra. María González López', 
    'Laboratorio Clínico San José', 
    'Examen de Orina Completo', 
    'Análisis físico, químico y microscópico de orina',
    'Color: Amarillo claro, pH: 6.0, Densidad: 1.020, Proteínas: Negativo, Glucosa: Negativo',
    'PENDIENTE',
    TO_DATE('2024-11-03', 'YYYY-MM-DD'),
    'Muestra recibida en condiciones óptimas',
    'pH: 4.5-8.0, Densidad: 1.010-1.030',
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP
);

COMMIT;

SELECT * FROM resultados;

SELECT 
    COUNT(*) as total_resultados,
    SUM(CASE WHEN estado = 'PENDIENTE' THEN 1 ELSE 0 END) as pendientes,
    SUM(CASE WHEN estado = 'EN_PROCESO' THEN 1 ELSE 0 END) as en_proceso,
    SUM(CASE WHEN estado = 'COMPLETADO' THEN 1 ELSE 0 END) as completados,
    SUM(CASE WHEN estado = 'ENTREGADO' THEN 1 ELSE 0 END) as entregados,
    COUNT(DISTINCT laboratorio) as laboratorios_distintos
FROM resultados;