BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE usuarios CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE usuarios (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    rut VARCHAR2(12) NOT NULL UNIQUE,
    telefono VARCHAR2(15) NOT NULL,
    rol VARCHAR2(20) NOT NULL CHECK (rol IN ('ADMIN', 'MEDICO', 'PACIENTE')),
    activo NUMBER(1) DEFAULT 1 NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
o
CREATE INDEX idx_usuarios_email ON usuarios(email);
CREATE INDEX idx_usuarios_rut ON usuarios(rut);
CREATE INDEX idx_usuarios_rol ON usuarios(rol);

INSERT INTO usuarios (nombre, apellido, email, password, rut, telefono, rol, activo, fecha_registro, fecha_actualizacion)
VALUES ('Juan', 'Pérez García', 'juan.perez@laboratorio.cl', 'admin123', '12345678-9', '+56912345678', 'ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO usuarios (nombre, apellido, email, password, rut, telefono, rol, activo, fecha_registro, fecha_actualizacion)
VALUES ('María', 'González López', 'maria.gonzalez@laboratorio.cl', 'medico123', '98765432-1', '+56987654321', 'MEDICO', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO usuarios (nombre, apellido, email, password, rut, telefono, rol, activo, fecha_registro, fecha_actualizacion)
VALUES ('Carlos', 'Rodríguez Silva', 'carlos.rodriguez@email.cl', 'paciente123', '11223344-5', '+56911223344', 'PACIENTE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO usuarios (nombre, apellido, email, password, rut, telefono, rol, activo, fecha_registro, fecha_actualizacion)
VALUES ('Ana', 'Martínez Pérez', 'ana.martinez@email.cl', 'paciente456', '22334455-6', '+56922334455', 'PACIENTE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

COMMIT;

SELECT * FROM usuarios;

SELECT 
    COUNT(*) as total_usuarios,
    SUM(CASE WHEN rol = 'ADMIN' THEN 1 ELSE 0 END) as admins,
    SUM(CASE WHEN rol = 'MEDICO' THEN 1 ELSE 0 END) as medicos,
    SUM(CASE WHEN rol = 'PACIENTE' THEN 1 ELSE 0 END) as pacientes,
    SUM(CASE WHEN activo = 1 THEN 1 ELSE 0 END) as activos
FROM usuarios;